import { IOfferBlockItem } from '../../types';
import { SUBSCRIPTION_TYPE } from '../../constants';

export const ADDITIONAL_BALANCE_PRESET_DATA: IOfferBlockItem[] = [
  {
    title: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_100K.TITLE,
    id: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_100K.RNIAP_PRODUCT_ID,
    stripeId: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_100K.STRIPE_PRODUCT_ID,
  },
  {
    title: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_200K.TITLE,
    id: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_200K.RNIAP_PRODUCT_ID,
    stripeId: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_200K.STRIPE_PRODUCT_ID,
  },
  {
    title: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_300K.TITLE,
    id: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_300K.RNIAP_PRODUCT_ID,
    stripeId: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_300K.STRIPE_PRODUCT_ID,
  },
  {
    title: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_500K.TITLE,
    id: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_500K.RNIAP_PRODUCT_ID,
    stripeId: SUBSCRIPTION_TYPE.ADDITIONAL_BALANCE_500K.STRIPE_PRODUCT_ID,
  },
];

export const ADDITIONAL_TIME_PRESET_DATA: IOfferBlockItem[] = [];

export const ADDITIONAL_MARGIN_TRADING_AND_BALANCE_PRESET_DATA: IOfferBlockItem[] = [];
