import { IOfferBlockItem } from '../../types';
import { ONE_TIME_PURCHASE_TYPE } from '../../constants';

export const ADDITIONAL_BALANCE_PRESET_DATA: IOfferBlockItem[] = [
  {
    title: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_100K.TITLE,
    id: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_100K.RNIAP_PRODUCT_ID,
    stripeId: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_100K.STRIPE_PRODUCT_ID,
  },
  {
    title: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_200K.TITLE,
    id: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_200K.RNIAP_PRODUCT_ID,
    stripeId: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_200K.STRIPE_PRODUCT_ID,
  },
  {
    title: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_300K.TITLE,
    id: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_300K.RNIAP_PRODUCT_ID,
    stripeId: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_300K.STRIPE_PRODUCT_ID,
  },
  {
    title: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_400K.TITLE,
    id: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_400K.RNIAP_PRODUCT_ID,
    stripeId: ONE_TIME_PURCHASE_TYPE.ADDITIONAL_400K.STRIPE_PRODUCT_ID,
  },
];

export const ADDITIONAL_TIME_PRESET_DATA: IOfferBlockItem[] = [];

export const ADDITIONAL_MARGIN_TRADING_AND_BALANCE_PRESET_DATA: IOfferBlockItem[] = [];
