require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

# pod 'Highcharts'
# pod 'FBSDKCoreKit', :modular_headers => true
# pod 'FBSDKLoginKit', :modular_headers => true
# pod 'FBSDKShareKit', :modular_headers => true

# pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :tag => 'v7.1.1'
# pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :tag => 'v7.1.1'
# pod 'FBSDKShareKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :tag => 'v7.1.1'

target 'BeatTheMarket' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BeatTheMarketTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BeatTheMarket-tvOS' do
  # Pods for BeatTheMarket-tvOS

  target 'BeatTheMarket-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
