import { COLORS } from './colors';
import { ITheme } from './interface';

const COMMON_THEME: ITheme = {
  MENU: {
    ACTIVE_LABEL_COLOR: COLORS.CORNFLOWER_BLUE,
  },
  GAME_SCREEN: {
    LIST_VIEW_INDICATOR_POSITIVE_COLOR: COLORS.MOON_RAKER,
    LIST_VIEW_INDICATOR_TEXT_COLOR: COLORS.GRAY,
    NUMBER_INDICATOR_UP: COLORS.JEWEL,
    NUMBER_INDICATOR_DOWN: COLORS.VALENCIA,
    NUMBER_INDICATOR_CHANGE: COLORS.AZURE_RADIANCE,
    LIST_VIEW_ACTIVE_COLOR: COLORS.MOON_RAKER,
    BUTTON_UP_COLOR: COLORS.BILBAO,
    BUTTON_DOWN_COLOR: COLORS.PUNCH,
  },
  SETTINGS_SCREEN: {},
  SIGNIN_SCREEN: {},
};

export const LIGHT_THEME: ITheme = {
  MENU: {
    ...COMMON_THEME.MENU,
    INACTIVE_LABEL_COLOR: COLORS.BLACK,
    BACKGROUND_COLOR: COLORS.MERCURY,
  },
  GAME_SCREEN: {
    ...COMMON_THEME.GAME_SCREEN,
    BACKGROUND_COLOR: COLORS.MERCURY,
    VIEW_COLOR: COLORS.WHITE,
    TEXT_COLOR: COLORS.BLACK,
    LIST_VIEW_COLOR: COLORS.WHITE,
    LIST_VIEW_INDICATOR_NEGATIVE_COLOR: COLORS.MACARONI_AND_CHEESE,
  },
  SETTINGS_SCREEN: {
    ...COMMON_THEME.SETTINGS_SCREEN,
    BACKGROUND_COLOR: COLORS.MERCURY,
    VIEW_COLOR: COLORS.WHITE,
    SWITCH_TITLE_COLOR: COLORS.BLACK,
  },
  SIGNIN_SCREEN: {},
};

export const DARK_THEME: ITheme = {
  MENU: {
    ...COMMON_THEME.MENU,
    INACTIVE_LABEL_COLOR: COLORS.WHITE,
    BACKGROUND_COLOR: COLORS.EBONY_CLAY,
  },
  GAME_SCREEN: {
    ...COMMON_THEME.GAME_SCREEN,
    BACKGROUND_COLOR: COLORS.MIRAGE,
    VIEW_COLOR: COLORS.EBONY_CLAY,
    TEXT_COLOR: COLORS.WHITE,
    LIST_VIEW_COLOR: COLORS.EBONY_CLAY,
    LIST_VIEW_INDICATOR_NEGATIVE_COLOR: COLORS.MOON_RAKER,
  },
  SETTINGS_SCREEN: {
    ...COMMON_THEME.SETTINGS_SCREEN,
    BACKGROUND_COLOR: COLORS.MIRAGE,
    VIEW_COLOR: COLORS.EBONY_CLAY,
    SWITCH_TITLE_COLOR: COLORS.WHITE,
  },
  SIGNIN_SCREEN: {},
};
