default_platform(:ios)

def beta(scheme, bundleID)
  match(git_url: "git@github.com:twashing/beatTheMarketIosCerts.git",
      readonly: true,
      type: "appstore",
      app_identifier: [
        bundleID
    ])
    build_app(scheme: scheme)
end

platform :ios do
  
  desc "Push a new staging alpha build to TestFlight"
  lane :alphaBuild do
    app_identifier = "com.beatthemarket.beatthemarket"
    beta("BeatTheMarket", app_identifier)
    upload_to_testflight(app_identifier: app_identifier)
  end
end
